name: munirif

services:
  app:
    image: ghcr.io/munirif/munirif:latest
    container_name: munirif
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      - TZ=Europe/Berlin
      - MUNIRIF_DB_HOST=db
      - MUNIRIF_DB_PORT=5432
      - MUNIRIF_DB_NAME=munirif
      - MUNIRIF_DB_USER=munirif
      - MUNIRIF_DB_PASSWORD=munirif_password
    volumes:
      - ./data:/app/data