# Generated by Django 4.2.4 on 2023-08-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('problem', models.CharField(max_length=5000)),
                ('solution', models.CharField(max_length=5000)),
                ('budget', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
            ],
        ),
    ]
