# Generated by Django 4.2.4 on 2023-08-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_file_file_alter_proposal_capacity_development_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
