# Generated by Django 4.2.4 on 2023-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=64),
        ),
    ]
