# Generated by Django 4.2.4 on 2023-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_score_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
            ],
        ),
    ]
