# Generated by Django 4.2.4 on 2023-09-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
