# Generated by Django 4.2.4 on 2023-09-08 12:57

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PureWindowsPath('C:/Users/MY PC/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=64),
        ),
        migrations.AlterField(
            model_name='score',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
