# Generated by Django 4.2.4 on 2023-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profile_phone_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='Officer', max_length=32),
            preserve_default=False,
        ),
    ]
