# Generated by Django 4.2.4 on 2023-10-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='word_limit',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
