# Generated by Django 4.2.4 on 2024-04-18 02:58

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_proposal_team_members_remove_proposal_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PureWindowsPath('C:/Users/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='section',
            name='word_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
