# Generated by Django 4.2.4 on 2024-04-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_proposal_created_at_proposal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='review_stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
