# Generated by Django 4.2.4 on 2024-04-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_score_review_stop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='review_stop_time',
        ),
    ]
