# Generated by Django 4.2.4 on 2024-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_score_review_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
