# Generated by Django 4.2.4 on 2024-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_score_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
