# Generated by Django 4.2.4 on 2024-05-29 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_score_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 5, 9, 43, 577082, tzinfo=datetime.timezone.utc)),
        ),
    ]
