# Generated by Django 4.2.4 on 2024-06-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_call_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 9, 41, 17, 924415, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='section',
            name='ref',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='section',
            name='word_limit',
            field=models.IntegerField(default=500),
        ),
    ]
