# Generated by Django 4.2.4 on 2024-06-24 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_score_expires_at_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.call'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 18, 3, 770113, tzinfo=datetime.timezone.utc)),
        ),
    ]
