# Generated by Django 4.2.4 on 2024-06-26 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_score_expires_at_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('EDITING', 'EDITING'), ('PENDING', 'PENDING'), ('REVIEWING', 'REVIEWING'), ('REVIEWED', 'REVIEWED'), ('SELECTED', 'SELECTED')], default='EDITING', max_length=64),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 4, 46, 25, 844477, tzinfo=datetime.timezone.utc)),
        ),
    ]
