# Generated by Django 4.2.4 on 2024-06-26 04:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 4, 54, 11, 248131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.call')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
