# Generated by Django 4.2.4 on 2024-06-26 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_score_expires_at_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 5, 29, 31, 551198, tzinfo=datetime.timezone.utc)),
        ),
    ]
