# Generated by Django 4.2.4 on 2024-06-26 06:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_proposal_theme_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 6, 2, 16, 442990, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=64)),
                ('unit_cost', models.PositiveIntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
