# Generated by Django 4.2.4 on 2024-06-26 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_score_expires_at_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 10, 1, 15, 870586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=64)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='core.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
