# Generated by Django 4.2.4 on 2024-06-26 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_score_expires_at_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 10, 36, 26, 814251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
