# Generated by Django 4.2.4 on 2024-07-05 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_attachment_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 4, 33, 13, 393037, tzinfo=datetime.timezone.utc)),
        ),
    ]
