# Generated by Django 4.2.4 on 2024-07-06 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_file_attachment_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 6, 49, 8, 616167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ReportingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.call')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
