# Generated by Django 4.2.4 on 2024-07-06 07:40

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_attachment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 7, 40, 17, 414019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PureWindowsPath('C:/Users/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to='')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
                ('reporting_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reportingdate')),
            ],
        ),
    ]
