# Generated by Django 4.2.4 on 2024-07-08 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_section_lower_limit_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_score',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 6, 41, 33, 794098, tzinfo=datetime.timezone.utc)),
        ),
    ]
