# Generated by Django 4.2.4 on 2024-07-08 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_section_max_score_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('PI', 'PI'), ('Co PI', 'Co PI'), ('MEMBER', 'MEMBER')], default='PI', max_length=64),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 12, 26, 41, 596045, tzinfo=datetime.timezone.utc)),
        ),
    ]
