# Generated by Django 4.2.4 on 2024-07-10 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_score_expires_at_profiletheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profiletheme',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 5, 49, 46, 51513, tzinfo=datetime.timezone.utc)),
        ),
    ]
