# Generated by Django 4.2.4 on 2024-07-14 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_proposal_is_selected_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 2, 16, 13, 525516, tzinfo=datetime.timezone.utc)),
        ),
    ]
