# Generated by Django 4.2.4 on 2024-07-17 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_attachment_is_required_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 6, 39, 14, 939295, tzinfo=datetime.timezone.utc)),
        ),
    ]
