# Generated by Django 4.2.4 on 2024-08-30 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.theme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 3, 47, 51, 418132, tzinfo=datetime.timezone.utc)),
        ),
    ]
