# Generated by Django 4.2.4 on 2024-08-30 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_proposal_theme_alter_score_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 5, 8, 15, 967903, tzinfo=datetime.timezone.utc)),
        ),
    ]
