# Generated by Django 4.2.4 on 2025-04-13 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='current_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_call', to='core.call'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 11, 54, 51, 769291, tzinfo=datetime.timezone.utc)),
        ),
    ]
