# Generated by Django 4.2.4 on 2025-10-15 14:12

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_call_description_call_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='attachments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='attachments_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PurePosixPath('/home/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PurePosixPath('/home/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 14, 12, 41, 607034, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=64)),
                ('unit_cost', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
