# Generated by Django 4.2.4 on 2025-10-15 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_score_attachments_score_attachments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdate',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.call'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 17, 12, 44, 59835, tzinfo=datetime.timezone.utc)),
        ),
    ]
