# Generated by Django 4.2.4 on 2025-12-06 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_reportingdate_call_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='budget_allocation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 2, 11, 47, 53924, tzinfo=datetime.timezone.utc)),
        ),
    ]
