# Generated by Django 4.2.4 on 2025-12-06 02:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_proposal_budget_allocation_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='fund_allocation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 2, 39, 4, 292074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.budgetcategory'),
        ),
    ]
