# Generated by Django 4.2.4 on 2025-12-06 04:08

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_call_fund_allocation_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PurePosixPath('/home/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 4, 8, 26, 105272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proposal')),
            ],
        ),
    ]
