# Generated by Django 4.2.4 on 2025-12-06 04:18

import datetime
import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_report_template_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='template',
        ),
        migrations.AddField(
            model_name='reportingdate',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/proposal_files', location=pathlib.PurePosixPath('/home/samuelitwaru/Desktop/CODE/MuniRIF/media/proposal_files')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 4, 18, 31, 784728, tzinfo=datetime.timezone.utc)),
        ),
    ]
