# Generated by Django 4.2.4 on 2025-12-06 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_report_template_reportingdate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.budgetcategory'),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 4, 41, 10, 619449, tzinfo=datetime.timezone.utc)),
        ),
    ]
