# Generated by Django 4.2.4 on 2026-02-02 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_budget_budget_category_alter_score_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 1, 33, 35, 558528, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=64),
        ),
    ]
