# Generated by Django 4.2.4 on 2026-02-27 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_profile_settings_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='calls',
            field=models.ManyToManyField(blank=True, related_name='themes', to='core.call'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='budget_allocation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 3, 5, 3, 204331, tzinfo=datetime.timezone.utc)),
        ),
    ]
