# Generated by Django 4.2.4 on 2026-03-07 06:23

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_theme_calls_alter_proposal_budget_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='attachments_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='attachments_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='capacity_development_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='capacity_development_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='conflict_of_interest_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='conflict_of_interest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='detailed_budget_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='detailed_budget_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ethical_implications_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ethical_implications_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outputs_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outputs_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='problem_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='problem_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='scalability_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='scalability_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='solution_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='solution_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='summary_budget_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='summary_budget_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='team_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='workplan_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='workplan_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 6, 23, 54, 970225, tzinfo=datetime.timezone.utc)),
        ),
    ]
