# Generated by Django 4.2.4 on 2026-03-07 09:28

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_proposal_attachments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 9, 28, 39, 568955, tzinfo=datetime.timezone.utc)),
        ),
    ]
