# Generated by Django 4.2.4 on 2026-03-07 09:35

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_proposal_is_recommended_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_done_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 9, 35, 36, 595815, tzinfo=datetime.timezone.utc)),
        ),
    ]
