# Generated by Django 4.2.4 on 2026-03-07 10:48

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_proposal_is_done_screening_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('EDITING', 'EDITING'), ('SUBMITTED', 'SUBMITTED'), ('SCREENED', 'SCREENED'), ('REVIEWING', 'REVIEWING'), ('REVIEWED', 'REVIEWED'), ('SELECTED', 'SELECTED')], default='EDITING', max_length=64),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 10, 48, 45, 298577, tzinfo=datetime.timezone.utc)),
        ),
    ]
