# Generated by Django 4.2.4 on 2026-03-07 10:52

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_proposal_status_alter_score_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 10, 52, 50, 22969, tzinfo=datetime.timezone.utc)),
        ),
    ]
